[server]
enable = false
ip = "10.0.0.1"
port = "8888"
path = "/tmp/engine"

[multiEngines]
enable = false
number = 3
paths = ["/tmp/engine1", "/tmp/engine2", "/tmp/engine3"]

[cli]
enable = true
path = "./dummy_engine"
