[server]
enable = false
ip = "10.0.0.1"
port = "8888"
path = "/tmp/engine"

[multiEngines]
enable = true
number = 3

[[multiEngines.path]]
path = "/tmp/engine1"

[[multiEngines.path]]
path = "/tmp/engine2"

[[multiEngines.path]]
path = "/tmp/engine3"

[cli]
enable = true
path = "/tmp/engine"
