#!/usr/bin/env bash
#
# Build a static binary for the host OS/ARCH
#

set -eu -o pipefail


source ./scripts/.variables


echo "Building statically linked $TARGET"
export CGO_ENABLED=0
go get -u github.com/BurntSushi/toml
go build -o "${TARGET}" --ldflags "${LDFLAGS}" "${SOURCE}"